version: '3'

services:
    # Development related
    db:
        build:
            context: .
            dockerfile: ./docker/db/Dockerfile-postgres
    log:
        build:
            context: .
            dockerfile: ./docker/log/Dockerfile
    build-deps:
        build:
            context: .
            dockerfile: ./docker/deps/Dockerfile
        volumes:
            - ./vendor:/opt/ext_vendor
        command: /opt/copy_deps.sh
    dev-server:
        build: .
        command: ./start_dev_server.sh
        ports:
            - "8000:80"
        volumes:
            - ./src:/opt/code
        depends_on:
            - db
    test:
        build: .
        entrypoint: pytest
        volumes:
            - ./src:/opt/code
        depends_on:
            - db
            - build-deps

    # Producion related
    server:
        build: .
        command: /opt/server/start_server.sh
        ports:
            - "8080:80"
        depends_on:
            - db
            - log
